version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.yml
    container_name: todo_django
    restart: always
    env_file: .env
    depends_on:
      - db
    expose:
      - "8000"
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:latest
    container_name: todo_nginx
    restart: always
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"

volumes:
  postgres_data:
