# Base image
FROM python:3.10

# Set working directory
WORKDIR /api

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose port for Gunicorn
EXPOSE 8000

# RUN python manage.py migrate

# Run Gunicorn server
CMD ["gunicorn", "api.wsgi:application", "--bind", "0.0.0.0:8000"]
